<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net48;net6.0-windows;net8.0-windows</TargetFrameworks>
    <LangVersion>8.0</LangVersion>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <Version>$([System.DateTime]::UtcNow.ToString("yyyy.MMdd.HHmmss"))</Version>
  </PropertyGroup>
</Project>
