<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net48;net6.0-windows7.0;net8.0-windows7.0</TargetFrameworks>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <Version>1.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Deterministic>false</Deterministic>
    <ApplicationIcon>p4.ico</ApplicationIcon>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net48'">
    <DefineConstants>$(DefineConstants);NET48</DefineConstants>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(TargetFramework)' == 'net6.0-windows7.0'">
    <DefineConstants>$(DefineConstants);NET6_0_WINDOWS</DefineConstants>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(TargetFramework)' == 'net8.0-windows7.0'">
    <DefineConstants>$(DefineConstants);NET8_0_WINDOWS</DefineConstants>
  </PropertyGroup>
  
  <ItemGroup>
    <Content Include="p4.ico" />
  </ItemGroup>
</Project>
